### ISSUE TITLE
bibparse.py - pb de parser

### ISSUE THREAD

**Issue by lakonis** [PookMook/Scripts#1]
J'ai lancé le script qui a parfaitement fonctionné sur 3 articles, avant de s'arrêter sur le SP1245 (cf ci-dessous):

```bash
> python ./bibparse.py ./
cleaning ./-clean/
Parsing files in .//
./SP1225.bib
./SP1255.bib
./SP1228.bib
./SP1245.bib
Traceback (most recent call last):
  File "./bibparse.py", line 31, in <module>
    bib_database = bibtexparser.load(bibtex_file)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/__init__.py", line 71, in load
    return parser.parse_file(bibtex_file)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bparser.py", line 165, in parse_file
    return self.parse(file.read(), partial=partial)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bparser.py", line 147, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibtexexpression.py", line 263, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 2163, in parseFile
    return self.parseString(file_contents, parseAll)
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3858, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3858, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/home/nicolas/.local/lib/python2.7/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibtexexpression.py", line 260, in _string_expr_parse_action
    return self._string_expr_parse_action_fun(s, l, t)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bparser.py", line 184, in <lambda>
    BibDataStringExpression.expression_if_needed(t)))
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bparser.py", line 178, in <lambda>
    maybe_interpolate = lambda expr: as_text(expr)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibdatabase.py", line 223, in as_text
    return text_string_or_expression.get_value()
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibdatabase.py", line 184, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibdatabase.py", line 150, in expand_string
    return string_or_bibdatastring.get_value()
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibdatabase.py", line 131, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "/home/nicolas/.local/lib/python2.7/site-packages/bibtexparser/bibdatabase.py", line 104, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: u'feb'
```

Après quelques tests, je me suis rendu compte que le parser ne parsait pas la donnée `month` ou `Month` (absente des 3 fichiers successful), si elle n'était pas dans des accolades.. Or par défaut, elle semble ne l'être jamais, sauf cas exceptionnel (mois en français ou en chiffre).

Faut-il préprocesser les bib pour ajouter les accolades ou corriger le parser pour qu'il traite correctement les `month = dec,` ?

**Comment by timoguic** [comment]
Problème de config dans le parser, il faut utiliser common_strings = True

(cf [la doc - encadré bleu](https://bibtexparser.readthedocs.io/en/master/tutorial.html#step-2-parse-it))

**Comment by PookMook** [comment]
yes, il faut ajouter un parser, je vais lui mettre ca

**Comment by PookMook** [comment]
Ajouté dans https://github.com/PookMook/Scripts/commit/e9604cb3557db32805da575f01972c54c598f9fd

**Comment by lakonis** [comment]
merci @timoguic that did the trick. Je rajoute la ligne dans le script, mais je vous laisse vérifier parce que c'est ptetre crado.

**Comment by PookMook** [comment]
doit etre résolu dans https://github.com/PookMook/Scripts/commit/9748d880c73dd77ce8c4fa8d4868f55c21bf6fbe
